### PR TITLE
Updated to reference LLBLGen 5.3.x and framework 4.5.2

### PR DESCRIPTION
**Pull request by jsobell**
Simply updated references

### CODE REVIEW

**Comment by FransBouma** [comment]
Thanks :) 

I have to admit, I'm surprised people use it through nuget, it's just 1 code file, but nevertheless, I'll create an updated package. As I think it can be made netstandard2.0 compatible too, I'll change it to that target before pushing the new package. (so multi-targeting, as 4.5.2 doesn't support netstandard 2.0)

**Comment by jsobell** [comment]
Yes, I often feel the same when there's a package with a tiny DLL, but I have seen examples where people have embedded the source file in a nuget package and the script has dropped it into the source folder.
I like that idea, as there's no compiled package dependency involved.
Why use nuget at all? Well I think it's simply the ability to share updates painlessly(ish) :)

**Comment by FransBouma** [comment]
I'll merge it, so it should be kept open :) I don't like packages with scripts, to be honest. I know I'm in the minority, and perhaps it's silly (you trust the dll/code, but not the installation script...) but it wouldn't be the first time an installer wipes a harddrive.

**Comment by jsobell** [comment]
It's not actually like that, as you don't need a runnable script in the installation. All you do is add your script file reference to be delivered to a folder called 'content' and it is automatically added to your project root.
The only possible side issue is that if the user manually modifies the source then the changes will be lost.

`LLBLGen.Linq.Prefetch.nuspec` :
```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
    <metadata>
		<id>LLBLGen.Linq.Prefetch</id>
		<version>1.0.0.7</version>
		<authors>Richard Hopton</authors>
		<owners>Solutions Design bv</owners>
		<description>Prefetch extensions for LLBLGen Pro.</description> 
		<projectUrl>http://github.com/SolutionsDesign/LLBLGen.Linq.Prefetch</projectUrl>
		<licenseUrl>http://www.opensource.org/licenses/mit-license.php</licenseUrl>
		<iconUrl>http://www.llblgen.com/Pics/LLBLGenLogo_32x32.png</iconUrl>
		<tags>LLBLGen Pro Prefetch O/RM</tags>
		<language>en-us</language>
        <copyright>(c)2002-2018 Solutions Design bv</copyright>
		<dependencies>
			<dependency id="SD.LLBLGen.Pro.ORMSupportClasses" version="[5.0.0, 6.0)" />
		</dependencies>		
  </metadata>
	<files>
		<file src=".\PrefetchExtensions.cs" target="content\LLBLGenExtensions\"/>
	</files>
</package>
```

**Comment by FransBouma** [comment]
Neat! I didn't know that :) Thanks for the heads up. Will ponder a bit about changing it to a source only distribution or keeping the dll and will fix the package online.

**Comment by FransBouma** [comment]
Decided to update the nuget dll instead of distributing as source, as updates to the source will be overwritten with an updated package, which is likely unexpected by the user. v1.0.0.7 referencing v5.3.3 is now live

**Pull request merged**
